import './globals.scss'

import Header from '@/src/app/Header'
import QueryProvider from '@/src/components/Providers/QueryProvider'
import UserSessionProvider from '@/src/components/Providers/SessionProvider'
import { ThemeProvider } from '@/src/components/Providers/ThemeProvider'
import { ReactQueryDevtools } from '@tanstack/react-query-devtools'
import { SpeedInsights } from '@vercel/speed-insights/next'
import { GeistMono } from 'geist/font/mono'
import { GeistSans } from 'geist/font/sans'
import type { Metadata } from 'next'
import { Toaster } from 'sonner'

export const metadata: Metadata = {
    title: 'NextDocs',
    description: 'Generated by create next app',
}

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html
            lang="en"
            className={`${GeistSans.variable} ${GeistMono.variable}`}>
            <UserSessionProvider>
                <QueryProvider>
                    <body className="bg-background">
                        <ThemeProvider
                            attribute="class"
                            defaultTheme="system"
                            enableSystem
                            disableTransitionOnChange>
                            <Toaster
                                position="top-center"
                                richColors
                                visibleToasts={5}
                            />
                            <Header />
                            <main className="flex h-[calc(100vh-50px)] w-full justify-center">
                                {children}
                            </main>

                            {/* <ReactQueryDevtools initialIsOpen={false} /> */}
                            <SpeedInsights />
                        </ThemeProvider>
                    </body>
                </QueryProvider>
            </UserSessionProvider>
        </html>
    )
}
